### ISSUE TITLE
[Proposal] add `be` function to `BeEqual` interface

### ISSUE THREAD

**Issue by sergeibukharov** [from-source/kiwi#12]
In order to maintain fluent DSL, I suggest adding `be` function to `BeEqual` interface.

```
true.should() be true
"Hello".should() be "Hello"
```

interface BeEqual<T, R : BeEqual<T, R>> {
   
    infix fun be(expected: T): R = beEqual()
}

As a counterpart we may add `notBe`
``` 
"Hello".should() notBe "World"
```

**Comment by torczuk** [comment]
Do you suggest `be` to be an alias for `beEqual` or rename `beEqual` to `be`?
