### ISSUE TITLE
avoid using () for `something.should()`

### ISSUE THREAD

**Issue by sergeibukharov** [from-source/kiwi#20]
It is possible to avoid using () when we call `should`.

**Why?**
instead of 
`myString.should() be "Hello`
we can use
`myString.should be "Hello`
I think it is a little bit closer to natural language,

**How to implement it?**

instead of adding external function 
`fun String.should() = StringShould(this)`

we can add
```
val String.should: AnyShould
 get() = AnyShould(this)
```
**The question us**
 - do you like  new staff?
 - if yes, should we remove `shuold()` staff?

**Comment by torczuk** [comment]
to summarize  
**single should**
```
myString.should() be "Hello"
```
vs
```
myString.should be "Hello"
```

**multi line should**
```
animals.should()
                .haveSize(4)
                .contain(flamingo)
                .beSorted { it.weight }
                .filtered { animal -> animal.mammal }
                .matchAny { animal -> animal.heavy() }
```
vs
```
animals.should
                .haveSize(4)
                .contain(flamingo)
                .beSorted { it.weight }
                .filtered { animal -> animal.mammal }
                .matchAny { animal -> animal.heavy() }
```
I think we can proceed with `should` instead of `should()`

One think to clarify. In your comment instead of 
```
val String.should: AnyShould
```
we should have, right?
```
val String.should: StringShould
   get() = StringShould(this)
```
